### PR TITLE
Make RPresto compatible with new Presto JSON data format and dbplyr 2.5.0

### LINKED ISSUE #272: `copy_to` is adding extra `"` to table name
I am creating a Trino table from a select statement on another Trino table. It renders the wrong sql script which adds extra `"` wrapping the table name.
```
httr::set_config(
  httr::config(
    httpauth=1,
    userpwd='user:password',
    ssl_verifypeer=0
  )
)

con = DBI::dbConnect(
  drv = RPresto::Presto(),
  host="https://trinohost",
  port=8443,
  user=user,
  password=password,
  catalog="hive",
  schema=my_schema,
  bigint="numeric"
)

person <- dplyr::tbl(con, "person")

dplyr::copy_to(dest = con, df = person, name = "person_new")

```

The sql it renders:
```
CREATE TABLE """person_new""" AS SELECT * FROM "person"
```

The table_name got created is `"person_new"` instead of `person`. 
```
dplyr::tbl(con,'person')  # failed
dplyr::tbl(con,'"person_new"') # succeed
```

Version:
```
Browse[1]> packageVersion('RPresto')
[1] ‘1.4.6’
Browse[1]> packageVersion('dbplyr')
[1] ‘2.5.0’
Browse[1]> packageVersion('DBI')
[1] ‘1.2.2’
Browse[1]> packageVersion('dplyr')
[1] ‘1.1.4’
```

### PR DESCRIPTION
**Pull request by jarodmeng**
There have been some changes to Presto and `dbplyr` which result in RPresto 1.4.6 having errors. This PR combines a few commits to solve those issues and make RPresto compatible again.

This PR should fix #272, #274, and #277.

### CODE REVIEW

File: R/sqlCreateTableAs.R [hunk 1]
```diff
@@ -31,7 +31,11 @@ setGeneric("sqlCreateTableAs",
 #' @rdname PrestoConnection-class
 #' @usage NULL
 .sqlCreateTableAs <- function(con, name, sql, with = NULL, ...) {
-  name <- DBI::dbQuoteIdentifier(con, name)
+  if (inherits(name, "dbplyr_table_path")) { # dbplyr >= 2.5.0
+    name <- dbplyr::table_path_name(name, con)
+  } else {
+    name <- DBI::dbQuoteIdentifier(con, name)
```
Comment (willshen99) [inline R/sqlCreateTableAs.R:37]: I think this is still breaking for dbplyr < 2.5.0 and DBI >= 1.2.0

Comment (jarodmeng) [reply R/sqlCreateTableAs.R:37]: Can you be more specific about the breaking? I ran all the unit tests with dbplyr 2.4.0 and DBI 1.2.3 and all tests passed.
